### ISSUE TITLE
Test multi-tenancy

### ISSUE THREAD

**Issue by jeremi** [OpenSPP/openspp-base#26]
We need to test the multi-tenant features of Odoo. In particular we need to check if we get in trouble with the task queue.
So test:
- 1 Odoo instance + multiple DB
- 1 Odoo instance + multi company

**Comment by emjay0921** [comment]
1 Odoo instance with multiple DB is good.

**Comment by emjay0921** [comment]
Findings (September 27, 2023) for Multi-company:
1. Individual and Group records can be seen on multiple company
2. Programs records can be seen on multiple company

**Comment by jeremi** [comment]
@emjay0921 What about the task queue?
And need to test all

**Comment by emjay0921** [comment]
Since @nhatnm0612 is testing the task queue in multi db, I tested the task queue in multi-company. So far it is working fine with my local server but I haven't got to test it via docker if its the same result. Maybe @reichie020212 can test this part since he is using docker. I tested also other modules with the multi-company and I think there's no problem, just needed to fix the record rules to properly segregates the specific records for the specific company. So far all is good with the multi-company.

**Comment by dasunhegoda** [comment]
@reichie020212 : once your current tasks are over, could you please check the above and share the findings here? You can talk to @emjay0921 before starting the tasks to get an update.

**Comment by dasunhegoda** [comment]
@reichie020212 @emjay0921 : Can you update your finding and close this ticket?

**Comment by emjay0921** [comment]
Hello @dasunhegoda I'll re-test this on Odoo 17 and will comment the new findings here.
