### ISSUE TITLE
Review the repos/modules from OpenG2P related to payments

### ISSUE THREAD

**Issue by dasunhegoda** [OpenSPP/openspp-base#45]
1. https://github.com/OpenG2P/openg2p-program/tree/15.0-develop/g2p_payment_cash
2. https://github.com/OpenG2P/social-payments-account-registry
3. https://github.com/OpenG2P/g2p-payments-bridge
4. https://github.com/OpenG2P/g2p-cash-transfer-bridge
5. https://github.com/openg2p/spar-ui

Provide feedback on an evaluation's usefulness and intent.

Ref: https://github.com/sunbird-RC/g2p-mapper-registry

**Comment by gonzalesedwin1123** [comment]
Here are my findings:

**1. https://github.com/OpenG2P/openg2p-program/tree/15.0-develop/g2p_payment_cash**
Similar to the default cash entitlement module but it generates payment files using the g2p_payment_files module. The payment files will be used for the disbursements of cash.

**2. https://github.com/OpenG2P/social-payments-account-registry**
This module that was created for the Philippines DSWD Financial assistance program.
It provides an API using Pydantic for the self-service financial assistance request and status monitoring. 

**3. https://github.com/OpenG2P/g2p-payments-bridge**
None-Odoo python codes. This provides an API for cash transfer. It also uses Pydantic. 

I think this requires actual testing in a test environment. If needed, I can setup a test environment to discover further the features of this.

**4. https://github.com/OpenG2P/g2p-cash-transfer-bridge**
None-Odoo python codes. Same as number 3: https://github.com/OpenG2P/g2p-payments-bridge

**5. https://github.com/openg2p/spar-ui**
None-Odoo typescript codes. Social Protection Account Registry Self-Service Portal. 
It uses the API in 2. https://github.com/OpenG2P/social-payments-account-registry

**Comment by dasunhegoda** [comment]
@gonzalesedwin1123 Thanks for the feedback.

Could you comment on the code reusability? Have they followed the Odoo best practices?

**Comment by gonzalesedwin1123** [comment]
@dasunhegoda. For the odoo modules, the OpenG2P team followed the OCA coding standard, though there are issues with test coverage. All odoo modules automated tests are failing.

The same automated test issues are also present in the None-Odoo python codes.

I tried to follow the instructions in setting up the API backend (None-Odoo python codes) but I am getting some issues in the installation. I need more time to explore so that I will be able to see exactly how all of these functions.

Given all of these findings I cannot recommend the use of these for now in our implementations.
